version: '3.3'
services:
  nginx:
    image: nginx:1.19.4-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      LANG: C.UTF-8
    volumes:
      - '~/nginx-${SITE_NAME}/src:/src:cached'
      - '~/certbot:/certbot:cached'
      - '~/.site/conf.d:/etc/nginx/conf.d:cached'
      - '~/log:/log:cached'
      - '/etc/localtime:/etc/localtime:ro'
    restart: always