version: '3.8'
services:
  db:
    image: 'jbergstroem/mariadb-alpine'
    volumes:
      - "~/mariadb-${SITE_NAME}:/var/lib/mysql:cached"
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWD}
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: ${DBPASSWD}
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
      LANG: C.UTF-8
    restart: unless-stopped

  wordpress:
    depends_on:
      - db
    image: docker.io/wordpress:5.5.3-php7.4-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: ${DBPASSWD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      LANG: C.UTF-8
    volumes:
      - "~/nginx-${SITE_NAME}/src:/var/www/html"
      - "./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
      - '~/log:/log:delegated'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped


