version: '3.8'
services:
  wp-db:
    container_name: ${SITE_NAME}_wp-db
    image: 'jbergstroem/mariadb-alpine'
    networks:
    - wp-db-net-c
    volumes:
      - ~/j.d/db.d/${SITE_NAME}:/var/lib/mysql:cached
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWD}
      MYSQL_DATABASE: wp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: ${DBPASSWD}
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
      LANG: C.UTF-8
    restart: unless-stopped

  wp:
    container_name: ${SITE_NAME}_wp
    depends_on:
      - wp-db
    image: docker.io/wordpress:php7.4-fpm-alpine
    networks: 
    - web-net-c
    - wp-db-net-c
    volumes:
      - ~/j.d/nginx.d/${SITE_NAME}:/var/www/html
      - ~/j.d/site/conf.d/${SITE_NAME}.php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ~/j.d/log:/log:cached
      - /etc/localtime:/etc/localtime
    environment:
      WORDPRESS_DB_HOST: ${SITE_NAME}_wp-db:3306
      WORDPRESS_DB_PASSWORD: ${DBPASSWD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_CONFIG_EXTRA: |
        define('WPLANG',           'ja');
        define('DB_CHARSET',       'utf8');
        define('DB_COLLATE',       'utf8_general_ci');
        define('FORCE_SSL_ADMIN',   true);
        define('CONCATENATE_SCRIPTS', false );
      LANG: C.UTF-8
    restart: unless-stopped

networks:
  web-net-c:
    external:
      name: web-net
  wp-db-net-c:
    external:
      name: wp-db-net