version: '3.8'
services:
  mariadb:
    container_name: db_${SITE_NAME}
    image: 'jbergstroem/mariadb-alpine'
    volumes:
      - "~/db.d/${SITE_NAME}:/var/lib/mysql:cached"
      - '/etc/localtime:/etc/localtime:ro'
    networks: 
      - wp-db-net-c
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWD}
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: ${DBPASSWD}
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
      LANG: C.UTF-8
    restart: unless-stopped

  wordpress:
    container_name: wp_${SITE_NAME}
    depends_on:
      - mariadb
    image: docker.io/wordpress:5.5.3-php7.4-fpm-alpine
    networks: 
    - web-net-c
    - wp-db-net-c
    volumes:
      - ~/nginx.d/${SITE_NAME}:/var/www/html
      - ~/.site/conf.d/${SITE_NAME}.php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ~/.site/conf.d/${SITE_NAME}.php-fpm.ini:/usr/local/etc/php-fpm.d/php-fpm.ini
      - '~/log:/log:cached'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      WORDPRESS_DB_HOST: db_${SITE_NAME}:3306
      WORDPRESS_DB_PASSWORD: ${DBPASSWD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_CONFIG_EXTRA: |
        define('WPLANG',           'ja');
        define('DB_CHARSET',       'utf8');
        define('DB_COLLATE',       'utf8_general_ci');
        define('FORCE_SSL_ADMIN',   true);
      LANG: C.UTF-8
    restart: unless-stopped

networks:
  web-net-c:
    external:
      name: web-net
  wp-db-net-c:
    external:
      name: wp-db-net