version: '3.8'
services:
  db:
    container_name: db_${SITE_NAME}
    image: 'jbergstroem/mariadb-alpine'
    volumes:
      - "~/mariadb-${SITE_NAME}:/var/lib/mysql:cached"
      - '/etc/localtime:/etc/localtime:ro'
    networks: 
      - wp-db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWD}
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: ${DBPASSWD}
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
      LANG: C.UTF-8
    restart: unless-stopped

  wp:
    container_name: wp_${SITE_NAME}
    depends_on:
      - db
    image: docker.io/wordpress:5.5.3-php7.4-fpm-alpine
    networks: 
    - web-net
    - wp-db
    volumes:
      - ~/nginx-${SITE_NAME}/src:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - '~/log:/log:delegated'
      - '/etc/localtime:/etc/localtime:ro'
    hostname: wp_${SITE_NAME}.host
    environment:
      WORDPRESS_DB_HOST: db_${SITE_NAME}:3306
      WORDPRESS_DB_PASSWORD: ${DBPASSWD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      LANG: C.UTF-8
    restart: unless-stopped

