version: '3.8'
services:
  nginx:
    image: nginx:1.19.4-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks: 
    - web-net-c
    environment:
      LANG: C.UTF-8
    volumes:
      - '~/j.d/nginx.d:/nginx.d:cached'
      - '~/j.d/certbot:/certbot:cached'
      - '~/j.d/site_name/conf.d:/etc/nginx/conf.d:cached'
      - './nginx.conf:/etc/nginx/nginx.conf:cached'
      - '~/j.d/log:/log:cached'
      - '/etc/localtime:/etc/localtime:ro'
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    restart: on-failure

networks:
  web-net-c:
    external:
      name: web-net